#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrdb -merge ~/.Xresources

nitrogen --restore
sh $HOME/.config/polybar/launch.sh
picom --experimental-backend

# Remap caps lock to escape
setxkbmap -option caps:escape


# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DP-3 -d 6 7 8 9 10

bspc config focus_follows_pointer true

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


