#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrdb -merge ~/.Xresources

nitrogen --restore
sh $HOME/.config/polybar/launch.sh


source ~/.cache/wal/colors.sh

bspc config active_border_color   $background
bspc config normal_border_color   $background
bspc config focused_border_color  $foreground
bspc config presel_feedback_color $color4

bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DP-3 -d 6 7 8 9 10

bspc config focus_follows_pointer true

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


