;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;     ______      __
;    / ________  / ____  __________
;   / /   / __ \/ / __ \/ ___/ ___/
;  / /___/ /_/ / / /_/ / /  (__  )
;  \____/\____/_/\____/_/  /____/
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;Catppuccin

[colors]
 bg = ${xrdb:color0:#222}
 tp= #002E3440
 trans = #FF00000
 fg =  ${xrdb:color7:#222}
 white = ${#000:xrdb:color7:#222}
 fg-alt = ${xrdb:color8:#222}
 blue-s = #B5E8E0
; blue = #2C6B95
 blue = ${xrdb:color1:#222}
 blue-alt = ${xrdb:color1:#222}
 red =  ${xrdb:color2:#222}
 green = ${xrdb:color6:#222}
 yellow = #FAE3B0
 cyan = ${xrdb:color1:#222}
 magenta = ${xrdb:color5:#222}
